language: php

sudo: true

php:
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=5.6.*
    - LARAVEL_VERSION=5.7.*
    - LARAVEL_VERSION=5.8.*

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - travis_retry composer self-update
  - composer install
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit --no-coverage
